name: Release #workflow name

# trigger condition
on:
  push:
    branches:
      - main #When codes are pushed into main branch

# prevent from concurrency
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: write #allow amend depot code
  pull-requests: write #allow create or amend PR
  id-token: write #allow get OIDC JWT

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get main son package version
        id: get_version
        run: |
          VERSION=$(node -p "require('./packages/@buaich/cli/package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Run changesets action
        uses: changesets/action@v1
        with:
          publish: pnpm ci:publish
          commit: "chore: update versions"
          title: "chore: update versions"
          createGithubReleases: aggregate
          githubReleaseName: "v${{steps.get_version.outputs.version}}"
        env:
          GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}
